"""Write the hero animation strip specs (category "anim") from the rig in _poses.json.

    python3 hero_anim.py                          # web/art/sprite/hero -> web/art/sprite/hero/anim
    python3 hero_anim.py --hero DIR --rig FILE    # other folders (tests)

One spec per static layer x anim: web/art/sprite/hero/anim/<layer>-<anim>.json, 4 frames of 48x64.
Each frame repaints the layer's regions (`use` + `clip`) shifted by that frame's offsets, so the strip
keeps the layer's exact colours and the game's hex recolour keeps working. Render them with render.py.
Exit code 1 (and nothing written) when a layer matches no body in the rig's "assign" table.
"""
import argparse
import fnmatch
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))


def body_of(layer, assign):
    for body, patterns in assign.items():
        if any(fnmatch.fnmatchcase(layer, p) for p in patterns):
            return body
    return None


def strip_spec(layer, anim, frames, rig, body):
    cw, ch = rig["cell"]
    regions = rig["bodies"][body]
    layers = []
    for i, frame in enumerate(frames):
        for region in rig["order"]:
            x, y, w, h = regions[region]
            dx, dy = frame[region]
            layers.append({"use": f"../{layer}.json", "clip": [x, y, w, h], "at": [cw * i + x + dx, y + dy]})
    return {
        "name": f"{layer}-{anim}",
        "category": "anim",
        "size": [cw * len(frames), ch],
        "_design": f"Generated by hero_anim.py from _poses.json: '{layer}' in the '{anim}' pose, {len(frames)} frames. Edit the rig, not this file.",
        "layers": layers,
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--hero", default=os.path.join(ROOT, "web", "art", "sprite", "hero"))
    ap.add_argument("--rig")
    args = ap.parse_args(argv)
    out_dir = os.path.join(args.hero, "anim")
    rig_path = args.rig or os.path.join(out_dir, "_poses.json")
    with open(rig_path) as f:
        rig = json.load(f)
    layers = sorted(f[:-5] for f in os.listdir(args.hero) if f.endswith(".json") and not f.startswith("_"))
    unassigned = [l for l in layers if body_of(l, rig["assign"]) is None]
    if unassigned:
        print(f"ERROR layers with no body in {rig_path} 'assign': {', '.join(unassigned)}")
        return 1
    os.makedirs(out_dir, exist_ok=True)
    written = 0
    for layer in layers:
        body = body_of(layer, rig["assign"])
        for anim, frames in rig["anims"].items():
            spec = strip_spec(layer, anim, frames, rig, body)
            with open(os.path.join(out_dir, f"{layer}-{anim}.json"), "w") as f:
                json.dump(spec, f, indent=1)
                f.write("\n")
            written += 1
    print(f"wrote {written} strip specs for {len(layers)} layers x {len(rig['anims'])} anims -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
